### ISSUE TITLE
pypi  telegram_sleuth error

### ISSUE THREAD

**Issue by 4Minato** [naufalmng/telegram-group-sleuth#1]
1.wget https://files.pythonhosted.org/packages/48/9a/32b9d5ccce82efeb649246b92193c4969bbee925c576c9c671e2884fb3a0/telegram_sleuth-0.0.1.post5-py3-none-any.whl
2.pip3 install telegram_sleuth-0.0.1.post5-py3-none-any.whl

got an error:
Processing ./telegram_sleuth-0.0.1.post5-py3-none-any.whl
ERROR: Package 'telegram-sleuth' requires a different Python: 3.6.9 not in '>=3.8'

**Comment by 4Minato** [comment]
I got the meaning of this error wrong and thought that this package needed version 3.6.9. 
A stupid mistake

**Comment by naufalmng** [comment]
XD, I've updated it to now support Python from version 3.6.
